import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | VibeFly",
  description: "Terms of Service for VibeFly",
};

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-background">
      <div className="mx-auto max-w-3xl px-6 py-16">
        <Link
          href="/"
          className="text-sm text-primary hover:underline"
        >
          &larr; Back to home
        </Link>

        <h1 className="mt-8 text-4xl font-bold tracking-tight text-foreground font-display">
          Terms of Service
        </h1>
        <p className="mt-2 text-muted-foreground">Last updated: April 2, 2026</p>

        <div className="mt-10 space-y-10 text-foreground/80 leading-relaxed">
          {/* 1 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              1. Acceptance of Terms
            </h2>
            <p className="mt-3">
              By accessing or using the VibeFly platform (&quot;Service&quot;),
              operated by VibeFly (&quot;we&quot;, &quot;us&quot;, or
              &quot;our&quot;), you (&quot;User&quot;) agree to be bound by
              these Terms of Service. If you do not agree with any part of these
              terms, you must not use our Service.
            </p>
            <p className="mt-3">
              By using our Service, you also agree to comply with the{" "}
              <a
                href="https://developers.facebook.com/terms/"
                className="text-primary hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                Meta Platform Terms
              </a>
              {" "}and the{" "}
              <a
                href="https://developers.facebook.com/devpolicy/"
                className="text-primary hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                Meta Developer Policies
              </a>
              , as our Service relies on the Meta Platform API. Any violation of
              Meta&apos;s terms may result in suspension of your access to
              VibeFly.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              2. Description of Service
            </h2>
            <p className="mt-3">
              VibeFly is a software-as-a-service platform that acts exclusively
              as a <strong>technical intermediary</strong> between the Meta
              (Facebook) Advertising API (Graph API) and AI-based tools
              compatible with the Model Context Protocol (MCP). Our Service
              facilitates the connection between your Meta advertising data and
              third-party AI models (such as Claude, ChatGPT, Cursor, and other
              MCP-compatible tools).
            </p>
            <p className="mt-3">
              <strong>
                We do not develop, train, operate, or control the AI models
              </strong>{" "}
              that process your advertising data. We are solely responsible for
              securely transmitting data between the Meta API and the AI tools
              you choose to connect.
            </p>
          </section>

          {/* 3 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              3. Nature of the Service &mdash; Intermediary Role
            </h2>
            <p className="mt-3">
              3.1. VibeFly acts as a <strong>bridge/connector</strong> between
              the Meta Advertising API and AI model providers. We do not make
              advertising decisions, create campaigns, modify budgets, or take
              any action on your Meta account on our own initiative. All actions
              are initiated by you through AI tools.
            </p>
            <p className="mt-3">
              3.2. We do <strong>not</strong> guarantee the accuracy, quality,
              adequacy, or reliability of any responses, suggestions, analyses,
              or actions generated by AI models connected through our platform.
            </p>
            <p className="mt-3">
              3.3. Any advertising decisions made based on AI model outputs
              &mdash; including but not limited to campaign creation, budget
              changes, audience targeting, ad creative modifications, and bid
              strategy adjustments &mdash; are the{" "}
              <strong>sole responsibility of the User</strong>.
            </p>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              4. Limitation of Liability
            </h2>
            <p className="mt-3">
              <strong>4.1. AI Model Outputs.</strong> VibeFly shall NOT be held
              liable for any losses, damages, costs, or expenses arising from
              errors, inaccuracies, hallucinations, or inappropriate suggestions
              generated by AI models. The AI models are provided by third
              parties and their behavior is outside our control.
            </p>
            <p className="mt-3">
              <strong>4.2. User Negligence.</strong> The User assumes full
              responsibility for reviewing and approving all actions before they
              are executed on their Meta advertising account. Failure to review
              AI-generated actions before execution constitutes user negligence,
              and VibeFly shall not be liable for any resulting damages.
            </p>
            <p className="mt-3">
              <strong>4.3. Financial Losses.</strong> VibeFly shall NOT be held
              liable for any direct, indirect, incidental, consequential,
              special, or exemplary financial losses resulting from:
            </p>
            <ul className="mt-2 list-disc pl-6 space-y-1">
              <li>
                Incorrect campaign configurations suggested or executed by AI
                models
              </li>
              <li>Excessive or inappropriate ad spend</li>
              <li>Poor ad performance or negative ROAS</li>
              <li>
                Account restrictions or bans imposed by Meta as a result of
                actions taken through AI tools
              </li>
              <li>Any errors in the Meta Graph API responses</li>
              <li>Service interruptions or downtime</li>
            </ul>
            <p className="mt-3">
              <strong>4.4. Maximum Liability.</strong> In any event, our total
              aggregate liability to you for all claims arising out of or
              related to the Service shall not exceed the amount you paid to us
              in the twelve (12) months preceding the claim.
            </p>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              5. User Responsibilities
            </h2>
            <p className="mt-3">5.1. You are solely responsible for:</p>
            <ul className="mt-2 list-disc pl-6 space-y-1">
              <li>The security of your Meta access tokens and API keys</li>
              <li>
                Reviewing all AI-generated suggestions before approval or
                execution
              </li>
              <li>
                Ensuring compliance with Meta Advertising Policies, applicable
                laws, and regulations
              </li>
              <li>
                Monitoring your advertising spend and campaign performance
              </li>
              <li>Maintaining the accuracy of your account information</li>
            </ul>
            <p className="mt-3">5.2. You must not use the Service to:</p>
            <ul className="mt-2 list-disc pl-6 space-y-1">
              <li>
                Violate Meta&apos;s Terms of Service or Advertising Policies
              </li>
              <li>Engage in fraudulent or deceptive advertising practices</li>
              <li>Circumvent rate limits or abuse the platform</li>
              <li>
                Attempt to reverse-engineer, decompile, or access our source
                code
              </li>
              <li>
                Share API keys or access credentials with unauthorized third
                parties
              </li>
            </ul>
            <p className="mt-3">
              5.3. You acknowledge and agree that{" "}
              <strong>you are the data controller</strong> of the advertising
              data processed through our platform. We act as a data processor
              only to the extent necessary to provide the Service.
            </p>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              6. No Warranty
            </h2>
            <p className="mt-3">
              6.1. The Service is provided on an <strong>&quot;AS IS&quot;</strong>{" "}
              and <strong>&quot;AS AVAILABLE&quot;</strong> basis, without
              warranties of any kind, either express or implied.
            </p>
            <p className="mt-3">6.2. We do not warrant that:</p>
            <ul className="mt-2 list-disc pl-6 space-y-1">
              <li>
                The Service will be uninterrupted, timely, secure, or error-free
              </li>
              <li>
                The results obtained through the Service will be accurate or
                reliable
              </li>
              <li>
                Any AI model connected through the Service will perform as
                expected
              </li>
              <li>
                The Meta Graph API will be continuously available or return
                accurate data
              </li>
            </ul>
            <p className="mt-3">
              6.3. We explicitly disclaim all warranties, including but not
              limited to implied warranties of merchantability, fitness for a
              particular purpose, and non-infringement.
            </p>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              7. Indemnification
            </h2>
            <p className="mt-3">
              You agree to indemnify, defend, and hold harmless VibeFly, its
              officers, directors, employees, agents, and affiliates from and
              against any and all claims, damages, losses, liabilities, costs,
              and expenses (including reasonable attorneys&apos; fees) arising
              from:
            </p>
            <ul className="mt-2 list-disc pl-6 space-y-1">
              <li>Your use or misuse of the Service</li>
              <li>Your violation of these Terms</li>
              <li>
                Actions taken on your Meta advertising account through AI tools
                connected via the Service
              </li>
              <li>
                Your violation of any applicable law, regulation, or Meta policy
              </li>
              <li>
                Any third-party claims related to your advertising activities
              </li>
            </ul>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              8. Third-Party Services
            </h2>
            <p className="mt-3">
              8.1. Our Service integrates with third-party services including
              but not limited to Meta (Facebook), Supabase, Cloudflare, Vercel,
              and Stripe. Your use of these services is subject to their
              respective terms of service and privacy policies.
            </p>
            <p className="mt-3">
              8.2. We are not responsible for the availability, accuracy, or
              reliability of any third-party service. Changes to third-party
              APIs (including the Meta Graph API) may affect the functionality
              of our Service.
            </p>
            <p className="mt-3">
              8.2.1. In particular, the Meta Graph API is subject to versioning,
              deprecation, and breaking changes at Meta&apos;s sole discretion.
              We will make commercially reasonable efforts to migrate to new API
              versions before deprecation deadlines, but we cannot guarantee
              uninterrupted service during such transitions. VibeFly shall not
              be liable for any loss of functionality, data access, or service
              disruption caused by changes to the Meta API.
            </p>
            <p className="mt-3">
              8.3. AI model providers (such as Anthropic, OpenAI, and others)
              have their own terms of service and usage policies. You are
              responsible for complying with the terms of the AI tools you
              choose to use with our platform.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              9. Data and Security
            </h2>
            <p className="mt-3">
              9.1. We implement reasonable security measures to protect your
              data as described in our Privacy Policy. However, no method of
              electronic transmission or storage is 100% secure.
            </p>
            <p className="mt-3">
              9.2. You are responsible for maintaining the confidentiality of
              your account credentials, API keys, and Meta access tokens.
            </p>
            <p className="mt-3">
              9.3. You must immediately notify us of any unauthorized use of
              your account or any security breach you become aware of.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              10. Subscription and Billing
            </h2>
            <p className="mt-3">
              10.1. Certain features of the Service are available under paid
              subscription plans. By subscribing, you agree to pay the
              applicable fees.
            </p>
            <p className="mt-3">
              10.2. Subscription fees are non-refundable except as required by
              applicable law.
            </p>
            <p className="mt-3">
              10.3. We reserve the right to modify pricing with at least 30
              days&apos; prior notice.
            </p>
          </section>

          {/* 11 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              11. Suspension and Termination
            </h2>
            <p className="mt-3">
              11.1. We may suspend or terminate your access to the Service at
              any time if:
            </p>
            <ul className="mt-2 list-disc pl-6 space-y-1">
              <li>You violate these Terms</li>
              <li>We detect abuse, fraud, or suspicious activity</li>
              <li>Required by law or a court order</li>
              <li>Meta revokes or restricts API access</li>
            </ul>
            <p className="mt-3">
              11.2. You may terminate your account at any time through your
              dashboard settings. Upon termination, your data will be deleted as
              described in our Privacy Policy.
            </p>
            <p className="mt-3">
              11.3. Sections 4, 6, 7, and 13 shall survive termination.
            </p>
          </section>

          {/* 12 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              12. Modifications to the Terms
            </h2>
            <p className="mt-3">
              We reserve the right to modify these Terms at any time. Material
              changes will be communicated via email or through a prominent
              notice on the platform at least 15 days before taking effect. Your
              continued use of the Service after the effective date constitutes
              acceptance of the modified Terms.
            </p>
          </section>

          {/* 13 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              13. Governing Law and Dispute Resolution
            </h2>
            <p className="mt-3">
              13.1. These Terms shall be governed by and construed in accordance
              with the laws of the Federative Republic of Brazil.
            </p>
            <p className="mt-3">
              13.2. Any disputes arising from these Terms or the use of the
              Service shall first be submitted to good-faith negotiation for a
              period of 30 days. If not resolved, disputes shall be submitted
              to the competent courts.
            </p>
            <p className="mt-3">
              13.3. Nothing in these Terms limits any rights you may have under
              applicable consumer protection laws.
            </p>
          </section>

          {/* 14 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              14. Severability
            </h2>
            <p className="mt-3">
              If any provision of these Terms is found to be invalid or
              unenforceable, the remaining provisions shall continue in full
              force and effect.
            </p>
          </section>

          {/* 15 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              15. Entire Agreement
            </h2>
            <p className="mt-3">
              These Terms, together with the Privacy Policy, constitute the
              entire agreement between you and VibeFly regarding the use of the
              Service.
            </p>
          </section>

          {/* 16 */}
          <section>
            <h2 className="text-2xl font-semibold text-foreground">
              16. Contact Us
            </h2>
            <p className="mt-3">
              If you have questions about these Terms of Service, please
              contact us:
            </p>
            <p className="mt-3">
              <strong>Email:</strong>{" "}
              <a
                href="mailto:contato@vibefly.app"
                className="text-primary hover:underline"
              >
                contato@vibefly.app
              </a>
            </p>
          </section>
        </div>

        <div className="mt-16 border-t border-border pt-8 text-center text-sm text-muted-foreground">
          <Link href="/" className="hover:underline">
            VibeFly
          </Link>
          <p className="mt-2 text-xs">
            CNPJ: 61.750.788/0001-48 &mdash; 61.750.788 TIAGO CASAS BURGER
          </p>
        </div>
      </div>
    </main>
  );
}
