import { build } from "esbuild";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENTRY = resolve(__dirname, "script.template.ts");
const OUT = resolve(__dirname, "script.generated.ts");

async function run(): Promise<void> {
  const result = await build({
    entryPoints: [ENTRY],
    bundle: true,
    minify: true,
    format: "iife",
    target: "es2020",
    write: false,
  });
  const code = result.outputFiles[0].text;
  const literal = JSON.stringify(code);
  const contents = `// Auto-generated by \`pnpm build:tracker\`. Do not edit.\nexport const TRACKER_SCRIPT = ${literal};\n`;
  writeFileSync(OUT, contents, "utf8");
  console.log(`Wrote ${OUT} (${code.length} bytes)`);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
